<nav class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="index.php?action=forum_allQuestions">Forum</a> -->
    <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="index.php?action=forum_allQuestions">Les questions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="index.php?action=publish-question">Publier une question</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="index.php?action=my-question">Mes questions</a>
        </li>
        <!-- <?php

              if (isset($_SESSION['auth'])) {

              ?>

              <li class="nav-item">
              <a class="nav-link" href="profile.php?id=<?= $_SESSION['id']; ?>">Mon Profil</a>
              </li>

           <?php
              }

            ?> -->

      </ul>
      <!-- <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>

<br><br>

<div class="container">

  <?php
  if (isset($errorMsg)) {
    echo $errorMsg;
  }

  if (isset($existingQuestion['date_publication'])) {
  ?>
    <section class="show-content">
      <h3><?= $existingQuestion['titre']; ?></h3>
      <hr>
      <p><?= $existingQuestion['contenu']; ?></p>
      <hr>
      <small><?= '<a href="index.php?action=forum_showMemberProfile.php&id=' . $existingQuestion['id_auteur'] . '">' . $existingQuestion['prenom_auteur'] . '</a> ' . $existingQuestion['date_publication']; ?></small>
    </section>
    <br>
    <?php
    //remplacement de if (isset($comments) && is_array($comments)) par if (!empty($comments) && is_array($comments))
    if (!empty($comments) && is_array($comments)) {
      foreach ($comments as $answer) {
    ?>
        <div class="card mb-3">
          <div class="card-header">
            <a href="index.php?action=forum_showMemberProfile.php&id=<?= $answer['id_auteur']; ?>"><?= $answer['prenom_auteur']; ?></a>
          </div>
          <div class="card-body">
            <?= $answer['contenu']; ?>

            <!-- Condition pour afficher le bouton "Supprimer réponse" seulement si l'utilisateur qui a rédigé la réponse est celui connecté -->
            <?php
            if (isset($_SESSION['login_id']) && $_SESSION['login_id'] == $answer['id_auteur']) {
            ?>
              <form method="POST" action="supprimer_reponse.php">
                <input type="hidden" name="answer_id" value="<?= $answer['id']; ?>">
                <!-- <button type="submit" class="btn btn-danger float-end" name="deleteResponse">Supprimer réponse</button> -->
                <a href="index.php?action=deleteComment&id=<?php echo $answer['id'] ?>&idquestion=<?php echo $existingQuestion['id'] ?>" onclick="return confirm('Etes vous sur de vouloir supprimer ce commentaire?')" class="btn btn-pink waves-effect waves-light"> <i class="mdi mdi-trash-can"></i> <span>Supprimer</span> </a>
              </form>
            <?php
            }
            ?>
            <!-- Fin de la condition -->

          </div>
        </div>
        <br>
    <?php
      }
    } else {
      echo "Aucun commentaire.";
    }
    ?>




    <section class="show-answers">

      <form class="form-group" method="POST">

        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Réponse :</label>
          <textarea name="answer" class="form-control"></textarea>
        </div><br>

        <button type="submit" class="btn btn-primary" name="validate">Commenter</button>

      </form>
      <br>
    </section>

  <?php
  }

  ?>


</div>