<nav class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="index.php?action=forum_allQuestions">Forum</a> -->
    <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="index.php?action=forum_allQuestions">Les questions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="index.php?action=publish-question">Publier une question</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="index.php?action=my-question">Mes questions</a>
        </li>
        <!-- <?php

            if(isset($_SESSION['auth'])){

              ?>

              <li class="nav-item">
              <a class="nav-link" href="profile.php?id=<?= $_SESSION['id']; ?>">Mon Profil</a>
              </li>

           <?php 
            }

            ?> -->
        
      </ul>
      <!-- <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>

<br><br>

<form class="container" method="POST" >

    <?php  
        if(isset($errorMsg)){
            echo '<p>'.$errorMsg.'</p>';
        }elseif(isset($successMsg)){
            echo '<p class="alert alert-info">'.$successMsg.'</p>';
        }    
    ?>


  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Titre de la question</label>
    <input type="text" class="form-control" name="title">
  </div>
  <br>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Description de la question</label>
    <textArea class="form-control" name="description"></textArea>
  </div>
  <br>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Contenu de la question</label>
    <textArea  class="form-control" name="content"></textArea>
  </div><br>
  
  <button type="submit" class="btn btn-primary" name="validate">Publier la question</button>
  
</form> <br><br><br><br><br><br><br>