
           <?php include $template1.'.phtml'?>
           
           <?php include $template.'.phtml' ?>
           
           
           
           
           
           
           

            <!-- FOOTER -->
            <footer>
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 widget-footer col-sm-3">
                            <h5> WOTE PAMODJA </h5>
                            <img src="" class="img-responsive space10" alt=""/>
                            <p> SUIVEZ NOUS : </p>
                            <div class="clearfix"></div>
                            <ul class="f-social">
                                <li><a href="https://www.facebook.com" class="fa fa-facebook"></a></li>

                                <li><a href="https://www.twitter.com" class="fa fa-twitter"></a></li>
                    
                                <li><a href="mailto:awotepamodja243@gmail.com" class="fa fa-envelope"></a></li>
                                
                                <li><a href="https://www.instagram.com" class="fa fa-instagram"></a></li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-sm-3 widget-footer">
                            <h5>Latest Tweets</h5>
                            <div class="tweet-info">
                                <div id="twitterfeed"></div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-3 widget-footer">
                            <h5>Nos activités</h5>
                            <ul class="widget-tags">
                                <li><a href="./categories-grid.html">friperie</a></li>
                                <li><a href="./categories-grid.html">sports</a></li>
                                <li><a href="./categories-grid.html">aide aux devoirs à domicile</a></li>
                                <li><a href="./categories-grid.html">Encadrement des enfants</a></li>
                                <li><a href="./categories-grid.html">Développement rural</a></li>
                                <li><a href="./categories-grid.html">Construction des écoles</a></li>
                                <li><a href="./categories-grid.html">Agriculture</a></li>
                                <li><a href="./categories-grid.html">Aide aux personnes démunies</a></li>
                              
                                
                            </ul>
                        </div>
                        <div class="col-md-3 col-sm-3 widget-footer">
                            <h5>Journal</h5>
                            <p>Inscrivez-vous à notre journal </p>
                            <form class="newsletter">
                                <input type="text" placeholder="Veillez saisir votre adresse mail ici.">
                                <button type="submit">Inscription !</button>
                            </form>
                        </div>
                    </div>
                </div>
            </footer>

            <!-- FOOTER COPYRIGHT -->
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7 col-sm-7">
                            <!-- <ul class="flinks">
                                <li><a href="./index.html">Plan du site</a></li>
                                <li><a href="./index.html">Termes de recherche</a></li>
                                <li><a href="./index.html">Recherche Avancée</a></li>
                                
                            </ul> -->
                            <br>
                            <p>Copyright 2023 &middot; Développé par <a href="https://mon-cv-r9qb-4iywyl10j-didiers-projects.vercel.app/">Didier Maba</a></p>
                        </div>
                        <div class="col-md-5 col-sm-5">
                            <img src="www/images/basic/" class="pull-right img-responsive payment" alt=""/>
                        </div>
                    </div>
                </div>
            </div>  

        </div>

       

        <div id="backtotop"><i class="fa fa-chevron-up"></i></div>



        <!-- Javascript -->
        <script src="www/js/jquery.js"></script>

       

        <script src="www/js/bootstrap.min.js"></script>        
        <script src="www/plugin/owl-carousel/owl.carousel.min.js"></script>
        <script src="www/js/bs-navbar.js"></script>
        <script src="www/js/vendors/isotope/isotope.pkgd.js"></script>
        <script src="www/js/vendors/slick/slick.min.js"></script>
        <script src="www/js/vendors/tweets/tweecool.min.js"></script>
        <script src="www/js/vendors/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
        <script src="www/js/vendors/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
        <script src="www/js/jquery.sticky.js"></script>
        <script src="www/js/jquery.subscribe-better.js"></script>
        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <script src="www/js/vendors/select/jquery.selectBoxIt.min.js"></script>
        <script src="www/js/main.js"></script>

    </body>
</html>