
            <!-- BREADCRUMBS -->
            <div class="bcrumbs">
                <div class="container">
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li>Connexion</li>
                    </ul>
                </div>
            </div>
            <div class="space10"></div>

            <!-- MY ACCOUNT -->
            <div class="account-wrap">
                <div class="container">
                
                    <div class="row">
                        <div class="col-sm-6 col-md-6">
                            <!-- HTML -->
                            <div id="account-id">
                                <h4 class="account-title"><span class="fa fa-chevron-right"></span>CONNEXION</h4>                                                                  
                                <div class="account-form">
                                   <?php if($connexion_error==1){ ?>
                                        <div class="alert alert-danger" role="alert">
                                          email ou mot de passe incorrect
                                          
                                        </div>
                                    <?php } ?>
                                   
                                    <form class="form-login" method="POST">                                        
                                        <ul class="form-list row">
                                           
                                            <li class="col-md-12 col-sm-12">
                                                <label >Email <em>*</em></label>
                                                <input name="cemail" required type="text" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Mot de passe <em>*</em></label>
                                                <input name="cpassword" required type="password" class="input-text">
                                            </li> 
                                           
                                        </ul>
                                        <div class="buttons-set">
                                            <button name="connexion" class="btn-black" type="submit"><span>login</span></button>
                                        </div>
                                    </form>
                                    
                                    
                                </div>                                    
                            </div>
                        </div>

                        <div class="col-sm-6 col-md-6">
                            <!-- HTML -->
                            <div id="account-id">
                                <h4 class="account-title"><span class="fa fa-chevron-right"></span>INSCRIPTION</h4>                                                                  
                                <div class="account-form">
                                    <?php if($inscription_ok==1){ ?>
                                        <div class="alert alert-success" role="alert">
                                          votre inscription a bien été prise en compte
                                          <br>
                                          veuillez vous connecter
                                        </div>
                                    <?php } ?>
                                    
                                    <form class="form-login" method="POST">                                        
                                        <ul class="form-list row">
                                           
                                            <li class="col-md-12 col-sm-12">
                                                <label >Civilité <em>*</em></label>
                                                <input name="civilite" required type="text" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Nom <em>*</em></label>
                                                <input name="nom" required type="text" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Prénom <em>*</em></label>
                                                <input name="prenom" required type="text" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Date de naissance<em>*</em></label>
                                                <input name="date_naissance" required type="date" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Email <em>*</em></label>
                                                <input name="email" required type="text" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Pseudo <em>*</em></label>
                                                <input name="pseudo" required type="text" class="input-text">
                                            </li> 
                                            <li class="col-md-12 col-sm-12">
                                                <label >Mot de passe <em>*</em></label>
                                                <input name="motdepasse" required type="password" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Adresse <em>*</em></label>
                                                <input name="adresse" required type="text" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Code postal <em>*</em></label>
                                                <input name="cp" required type="text" class="input-text">
                                            </li>
                                            <li class="col-md-12 col-sm-12">
                                                <label >Ville <em>*</em></label>
                                                <input name="ville" required type="text" class="input-text">
                                            </li>
                                           
                                        </ul>
                                        <div class="buttons-set">
                                            <button name="inscription" class="btn-black" type="submit"><span>Inscription</span></button>
                                        </div>
                                    </form>
                                    
                                    
                                    
                                </div>                                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix space20"></div>
