
<br><br>
<div class="container">

<?php 
if(isset($errorMsg)){ echo $errorMsg; }

if(isset($getHisQuestions)){ 
   ?>

                        <div class="card">
                            <div class="card-body">
                                <h4>@<?= $member_pseudo; ?></h4>
                                 <hr>
                                <p><?= $member_lastname . ' ' . $member_firstname; ?></p>
                            </div>

                        </div>
                        <br>
   
   <?php
       while($question = $getHisQuestions->fetch()){
            ?>

                        <div class="card">
                            <div class="card-header">
                                <?= $question['titre']; ?>
                            </div>
                            <div class="card-body">
                                <?= $question['description']; ?>
                            </div>
                            <div class="card-footer">
                               Par <?= $question['pseudo_auteur']; ?> le <?= $question['date_publication']; ?>
                            </div>

                        </div>
                           <br>
            
            
            <?php
        

       }

}

?>

</div>