<div class="content-page">
                <div class="content">

                    <div class="container-fluid">
                        
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    
                                    <h4 class="page-title">Ajouter un Administrateur</h4>
                                </div>
                            </div>
                        </div>     

                        <div class="row">
                            <div class="col-12">
                                <div class="card-box">
                                <?php if($ajouter_ok==1){ ?>
                                        <div class="alert alert-success" role="alert">
                                          L'ajout a bien été effectué
                                        </div>
                                    <?php } ?>
                                    <form class="form-horizontal" method="POST">
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label" for="simpleinput">Noms d'utilisateur</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="simpleinput" name="Noms">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label" for="simpleinput">Prénoms d'utilisateur</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="simpleinput" name="Prenoms">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label" for="simpleinput">Ville</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="simpleinput" name="Ville">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label" for="simpleinput">Email</label>
                                            <div class="col-sm-10">
                                                <input type="email" class="form-control" id="simpleinput" name="Email">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label" for="simpleinput">Mot de passe</label>
                                            <div class="col-sm-10">
                                                <input type="password" class="form-control" id="simpleinput" name="MotdePasse">
                                            </div>
                                        </div>



                                     <button type="submit" class="btn btn-primary" name="ajouter">Ajouter</button>
                                    </form>
        
                                </div> 
                            </div>
                        </div>
                        
                    </div> 
                </div> 

                <!-- Footer  -->
               <!-- <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                2018 - 2019 &copy; Greeva theme by <a href="">Coderthemes</a> 
                            </div>
                        </div>
                    </div>
                </footer> -->
                <!-- end Footer -->

            </div>
 <!-- Vendor js -->
        <script src="assets/js/vendor.min.js"></script>

        <!-- KNOB JS -->
        <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
        <!-- Chart JS -->
        <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

        <!-- Jvector map -->
        <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
        <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>
        
        <!-- Datatable js -->
        <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
        <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
        <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
        <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>
        
        <!-- Dashboard Init JS -->
        <script src="assets/js/pages/dashboard.init.js"></script>
        
        <!-- App js -->
        <script src="assets/js/app.min.js"></script>