
            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">Association Wote Pamodja</a></li>
                                            <li class="breadcrumb-item active">Tableau de bord</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Tableau de bord</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <div class="row">
                            <div class="col-xl-4">
        
                                <div class="card-box">
                                    
                                </div> <!-- end card-box-->
        
                            </div> <!-- end col -->
        
                            <div class="col-xl-4">
                                <div class="card-box">
                                    <div class="dropdown float-right">
                                      
                                    </div>
                                    <h1>Tableau de bord en maintenance</h1>
                                    <div class="row text-center">
                                        <div class="col-sm-4 mb-3">
                                           
                                        </div>
                                        <div class="col-sm-4 mb-3">
                                            
                                        </div>
                                        <div class="col-sm-4 mb-3">
                                           
                                        </div>
                                    </div>
                                    <div class="chartjs-chart high-performing-product">
                                        <canvas id="high-performing-product"></canvas>    
                                    </div>            
                                </div> <!-- end card-box-->
                            </div> <!-- end col -->
        
                            <div class="col-xl-4">
                                <div class="card-box">
                                    
                                </div> 
                            </div> 
                        </div>
                       
        
        
                        <div class="row">
                            <div class="col-xl-3">
                                <div class="card-box">

                                </div> <!-- end card-box -->
                            </div> <!-- end col -->
        
                            <div class="col-xl-6">
                                <div class="card-box">
                                   
                                    
                                    
                                    
                                </div> 
                            </div> 
        
                            <div class="col-xl-3">
                                <div>
                                   
                                </div> 
        
                                <div class="card-box">
                                    
                                </div> 
                            </div> 
                        </div>
                        <!-- fin de row -->
        
                        <div class="row">
                            <div class="col-xl-8">
                                <div class="card-box">
                                    
                                   
                                </div>  <!-- end card-box-->
                            </div> <!-- end col -->
        
                            <div class="col-xl-4">
                                <div class="card-box">
                                    
                                   
                                </div> <!-- end card-box-->
                            </div> <!-- end col-->
        
                        </div>
                        <!-- end row -->
                        
                    </div> <!-- container -->

                </div> <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12 text-center">
                               Association Wote Pamodja par <a href="">Didier MABA</a> 
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->

            </div>
 <!-- Vendor js -->
        <script src="assets/js/vendor.min.js"></script>

        <!-- KNOB JS -->
        <script src="assets/libs/jquery-knob/jquery.knob.min.js"></script>
        <!-- Chart JS -->
        <script src="assets/libs/chart-js/Chart.bundle.min.js"></script>

        <!-- Jvector map -->
        <script src="assets/libs/jqvmap/jquery.vmap.min.js"></script>
        <script src="assets/libs/jqvmap/jquery.vmap.usa.js"></script>
        
        <!-- Datatable js -->
        <script src="assets/libs/datatables/jquery.dataTables.min.js"></script>
        <script src="assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
        <script src="assets/libs/datatables/dataTables.responsive.min.js"></script>
        <script src="assets/libs/datatables/responsive.bootstrap4.min.js"></script>
        
        <!-- Dashboard Init JS -->
        <script src="assets/js/pages/dashboard.init.js"></script>
        
        <!-- App js -->
        <script src="assets/js/app.min.js"></script>