<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Woté Pamodja Admin</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="../www/images2/image5.png">

        <!-- App css -->
        <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
        <link href="assets/css/app.min.css" rel="stylesheet" type="text/css" />

    </head>

    <body class="authentication-bg authentication-bg-pattern d-flex align-items-center">

        <div class="home-btn d-none d-sm-block">
            <a href="index.html"><i class="fas fa-home h2 text-white"></i></a>
        </div>
        
        <div class="account-pages w-100 mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card">

                            <div class="card-body p-4">
                                
                                <div class="text-center mb-4">
                                    <a href="index.phtml">
                                        <span><img src="../www/images2/image5.png" alt="" height="70"></span>
                                    </a>
                                </div>
<?php if($connexion_error==1){ ?>
                                        <div class="alert alert-danger" role="alert">
                                          Nom d'utilisateur ou mot de passe incorrect
                                        </div>
                                    <?php } ?>
                                <form method="POST" class="pt-2">

                                    <div class="form-group mb-3">
                                        <label for="user">User Name</label>
                                        <input name="user" class="form-control" type="text" id="user" required="" placeholder="Nom d'utilisateur">
                                    </div>

                                    <div class="form-group mb-3">
                                        
                                        <label for="password">Password</label>
                                        <input name="password" class="form-control" type="password" required="" id="password" placeholder="Mot de passe">
                                    </div>

                                   

                                    <div class="form-group mb-0 text-center">
                                        <button class="btn btn-success btn-block" name="login" type="submit"> Connexion </button>
                                    </div>

                                </form>

                               
                                <!-- end row -->

                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <!-- Vendor js -->
        <script src="assets/js/vendor.min.js"></script>

        <!-- App js -->
        <script src="assets/js/app.min.js"></script>
        
    </body>
</html>